version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - python3 -m venv venv
      - source venv/bin/activate
      - pip3 install -r requirements.txt
  pre_build:
    commands:
      - git clone https://github.com/mathdube/sphinx-resume.git
      - cd sphinx-resume
  build:
    commands:
      - make html
  post_build:
    commands:
      - aws s3 cp s3://resume-project/id_rsa ~/id_rsa_git
      - echo -e "host github.com\n HostName github.com\n IdentityFile ~/id_rsa_git\n User root" > ~/.ssh/config
      - chmod 400 ~/id_rsa_git; chmod 400 ~/.ssh/config
      - git config --global user.email "math.dube@gmail.com"
      - git config --global user.name "AWS auto commit"
      - git add docs
      - git commit -m "Auto-built and commit new docs version."
      - git push ssh://git@github.com/mathdube/sphinx-resume.git