import json
import yaml
import datetime
import sphinx
from platform import python_version
from math import floor

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "Mathieu`s Resume"
copyright = '2020, Mathieu Dube'
author = 'Mathieu Dube'

today = datetime.datetime.now().strftime("%d %B, %Y	")

# The full version, including alpha/beta/rc tags
release = today


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

locale_dirs = ['locale/']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'bizstyle'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

first_day = datetime.datetime.fromtimestamp(1304254800)

years_experience = floor((datetime.datetime.now() - first_day).days / 365)


html_context = {
    'today': today,
    'years_experience': years_experience,
    'python_version': python_version(),
    'sphinx_version': sphinx.__version__,
}

def rstjinja(app, docname, source):
    """
    Followed the approach from https://www.ericholscher.com/blog/2016/jul/25/integrating-jinja-rst-sphinx/

    Thanks for the tip.
    """

    # Make sure we're outputting HTML
    if app.builder.format != 'html':
        return

    yml_file = f"source/locale/{language}.yaml"

    html_context["index_name"] = f"index_{language}.html" if language != "en" else "index.html"

    with open(yml_file, 'r', encoding='utf8') as f:
        cv_data = yaml.safe_load(f)
    html_context["cv_data"] = cv_data
    src = source[0]
    rendered = app.builder.templates.render_string(
        src, app.config.html_context
    )
    source[0] = rendered


def setup(app):
    app.connect("source-read", rstjinja)
    app.add_css_file('custom.css')





